In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from diffrl.env import DifferentiablePhysicsEnv
env = DifferentiablePhysicsEnv()

[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-n8o9p51o
[Taichi] version 0.7.26, llvm 10.0.0, commit e37bdb5e, linux, python 3.8.12
[I 01/19/22 23:44:44.522 20010] [shell.py:_shell_pop_print@35] Graphical python shell detected, using wrapped sys.stdout
[Taichi] Starting on arch=cuda
Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
{'width': (0.2, 0.2, 0.2), 'init_pos': (0.5, 0.1, 0.5), 'n_particles': 3000, 'color': 9868800}
Building primitive
action:
  dim: 6
  scale: (0.01, 0.01, 0.01, 0.01, 0.01, 0.01)
color: (0.8, 0.8, 0.8)
friction: 1.0
init_pos: (0.0, 0.1, 0.5)
init_rot: (1.0, 0.0, 0.0, 0.0)
lower_bound: (-1.0, -1.0, -1.0)
mass: 1.0
round: 0.01
shape: Box
size: (0.02, 0.15, 0.35)
upper_bound: (2.0, 2.0, 2.0)
variations: None
Building primitive
action:
  dim: 6
  scale: (0.01, 0.01, 0.01, 0.01, 0.01, 0.01)
color: (0.8, 0.8, 0.8)
friction: 1.0
init

In [3]:
state = env.get_state()

In [4]:
print(state['requires_grad'])

False


In [5]:
import numpy as np
import torch
import tqdm
from diffrl.utils import animate

state['requires_grad'] = False
env.set_state(state)
image_0 = []
states_0 = []
for i in tqdm.trange(50):
    env.step(torch.Tensor([1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0,0]))
    states_0.append(env._taichi_state())
    image_0.append(env.render(mode='array'))


state['requires_grad'] = True
env.set_state(state)
image_1 = []
states_1 = []
for i in tqdm.trange(50):
    env.step(torch.Tensor([1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0,0]))
    states_1.append(env._taichi_state())
    image_1.append(env.render(mode='array'))

animate([np.concatenate((a, b), axis=0) for a, b in zip(image_0, image_1)], _return=False)


  0%|          | 0/50 [00:00<?, ?it/s]

[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@100] [$9676] Local store may lose precision (target = f32, value = f64) at
[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@101] 

[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@100] [$9678] Local store may lose precision (target = f32, value = f64) at
[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@101] 

[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@100] [$9680] Local store may lose precision (target = f32, value = f64) at
[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@101] 

[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@100] [$9682] Local store may lose precision (target = f32, value = f64) at
[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@101] 

[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@100] [$9684] Local store may lose precision (target = f32, value = f64) at
[W 01/19/22 23:45:19.274 20010] [type_check.cpp:visit@101] 

[W 01/19/22 23:45:19.274 20010] [type_check.cpp:vi

100%|██████████| 50/50 [00:02<00:00, 18.60it/s]


animating animation.mp4
Moviepy - Building video animation.mp4.
Moviepy - Writing video animation.mp4



Moviepy - Done !
Moviepy - video ready animation.mp4


In [6]:
for s0, s1 in zip(states_0, states_1):
    x = s0['pos']
    y = s1['pos'].detach().cpu().numpy()
    assert np.linalg.norm(x-y) < 1e-4

[0.49914904 0.10947426 0.49819871]
tensor([0.4991, 0.1095, 0.4982])
1.0562549501539552e-06
[0.49914916 0.10943357 0.49819858]
tensor([0.4991, 0.1094, 0.4982])
1.0509219056674405e-06
[0.49914982 0.10944608 0.49819875]
tensor([0.4991, 0.1094, 0.4982])
1.0620880030823504e-06
[0.4991506  0.10948841 0.49819916]
tensor([0.4992, 0.1095, 0.4982])
1.0699287555812598e-06
[0.49915064 0.10949418 0.49819902]
tensor([0.4992, 0.1095, 0.4982])
1.062736732805513e-06
[0.4991501  0.10946083 0.49819828]
tensor([0.4992, 0.1095, 0.4982])
1.054670051796854e-06
[0.49914976 0.10944552 0.49819773]
tensor([0.4991, 0.1094, 0.4982])
1.0675186124711575e-06
[0.49914945 0.10946781 0.49819769]
tensor([0.4991, 0.1095, 0.4982])
1.0620316286317774e-06
[0.49914907 0.10948638 0.49819793]
tensor([0.4991, 0.1095, 0.4982])
1.0669358026385995e-06
[0.49914903 0.10947497 0.49819815]
tensor([0.4991, 0.1095, 0.4982])
1.0710663905179757e-06
[0.49914936 0.10945611 0.49819824]
tensor([0.4991, 0.1095, 0.4982])
1.0657456632395159e-06
[